# version format
version: 1.0.{build}

branches:
  only:
    - master
    - develop
build_script:
  - ps: .\build\runbuild.ps1
test: off
artifacts:
- path: .\Working\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/graphql-dotnet/api/v2/package
  api_key:
    secure: +l1vfBMajn1WfmXkQ2LdILKxK4fQ5AHSnnU1kf11Bn1xRGUOTCdPhLwHx232piEn
  skip_symbols: true
  on:
    branch: develop
