# version format
version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
branches:
  only:
    - master
    - develop
build_script:
  - ps: .\build\runbuild.ps1
test_script:
  - ps: .\build\uploadTestsToAppveyor.ps1
artifacts:
- path: .\Working\NuGet\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/graphql-dotnet/api/v2/package
  api_key:
    secure: +l1vfBMajn1WfmXkQ2LdILKxK4fQ5AHSnnU1kf11Bn1xRGUOTCdPhLwHx232piEn
  skip_symbols: true
  on:
    branch: develop
